// Generates src/icons.js from lucide-static (a dev dependency), copying in
// only the icons the app uses. Run with `npm run icons` after changing the
// mapping below or upgrading lucide-static.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const lucide = join(root, "node_modules", "lucide-static");

// Category name (or special section key) -> Lucide icon name.
// Browse the set at https://lucide.dev/icons
const MAPPING = {
  all: "layout-grid",
  frequent: "clock",
  favorites: "heart", // drawn filled, see FILLED
  custom: "pencil",

  Happy: "smile",
  Love: "heart",
  Hugs: "heart-handshake",
  Sad: "frown",
  Angry: "angry",
  Nervous: "droplet", // the sweat drop; "annoyed" looked too much like Shrug's "meh"
  Surprised: "circle-alert",
  Confused: "circle-question-mark",
  Shrug: "meh",
  "Table Flip": "flip-vertical-2",
  Blush: "smile-plus",
  Mischief: "ghost",
  Cute: "flower-2",
  Animals: "paw-print",
  Sparkle: "sparkles",
  "Dance & Music": "music",
  Food: "coffee",
  Fighting: "swords",
  "Thumbs Up": "thumbs-up",
  Sorry: "hand-heart",
  Running: "footprints",
  Sleepy: "moon",
  Greetings: "hand",
};

// Filled rather than outlined, to match the hearts on favorited tiles.
const FILLED = ["favorites"];

const version = JSON.parse(readFileSync(join(lucide, "package.json"), "utf8")).version;
const license = readFileSync(join(lucide, "LICENSE"), "utf8").trim();

const inner = (name) => {
  let svg;
  try {
    svg = readFileSync(join(lucide, "icons", `${name}.svg`), "utf8");
  } catch {
    throw new Error(`lucide-static ${version} has no icon named "${name}"`);
  }
  const body = svg.slice(svg.indexOf(">", svg.indexOf("<svg")) + 1, svg.lastIndexOf("</svg>"));
  return body.replace(/\s*\n\s*/g, "").trim();
};

const entries = Object.entries(MAPPING).map(([key, name]) => `  ${JSON.stringify(key)}: ${JSON.stringify(inner(name))},`);

const out = `// Generated by scripts/build-icons.mjs from lucide-static ${version}.
// Edit the mapping there and run \`npm run icons\`; don't edit by hand.
//
// Icons from Lucide (https://lucide.dev):
${license.split("\n").map((line) => `// ${line}`.trimEnd()).join("\n")}

const paths = {
${entries.join("\n")}
};

const FILLED = new Set(${JSON.stringify(FILLED)});

/** An <svg> element for a category (by name) or "all" / "frequent" /
 * "favorites" / "custom". Unknown names get the grid. */
export function categoryIcon(key, size = 15) {
  const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
  svg.setAttribute("viewBox", "0 0 24 24");
  svg.setAttribute("width", size);
  svg.setAttribute("height", size);
  svg.setAttribute("fill", FILLED.has(key) ? "currentColor" : "none");
  svg.setAttribute("stroke", "currentColor");
  svg.setAttribute("stroke-width", "2");
  svg.setAttribute("stroke-linecap", "round");
  svg.setAttribute("stroke-linejoin", "round");
  svg.setAttribute("aria-hidden", "true");
  svg.classList.add("cat-icon");
  svg.innerHTML = paths[key] ?? paths.all;
  return svg;
}
`;

writeFileSync(join(root, "src", "icons.js"), out);
console.log(`wrote src/icons.js: ${entries.length} icons from lucide-static ${version}`);
