// Each category has search keywords of its own; each item is either the
// kaomoji text or [text, "extra keywords"] for words specific to that one.
// Keywords are matched by prefix, so "sle" finds sleepy and "hu" finds hug.

export const categories = [
  {
    name: "Happy",
    keywords: "happy joy glad yay smile excited grin cheerful laugh laughing lol haha",
    items: [
      ["(๑˃ᴗ˂)ﻭ", "cheer fist"],
      ["＼(^o^)／", "hooray arms"],
      ["(★^O^★)", "star"],
      ["(*≧▽≦)", "laugh"],
      ["٩(◕‿◕)۶", "cheer"],
      ["(⌒▽⌒)☆", "star"],
      ["ヽ(・∀・)ﾉ", "arms"],
      ["(*´▽`*)", "content"],
      ["(๑˘︶˘๑)", "content peaceful"],
      ["＼(￣▽￣)／", "hooray arms"],
      "(≧◡≦)",
      "(o^▽^o)",
      ["٩(^‿^)۶", "cheer"],
      ["٩(｡•́‿•̀｡)۶", "cheer proud"],
      ["(✿◠‿◠)", "flower"],
      "(＾▽＾)",
      ["ヽ(>∀<☆)ノ", "star"],
      ["o(≧▽≦)o", "squeal"],
      "(*^▽^*)",
      ["(´｡• ᵕ •｡`)", "soft"],
      ["(≧∇≦)", "laugh"],
      ["(*≧ω≦*)", "squee"],
      ["(ﾉ≧∀≦)ﾉ", "laugh"],
      "(๑>◡<๑)",
      ["(^_^)", "simple"],
    ],
  },
  {
    name: "Love",
    keywords: "love heart crush adore affection romance",
    items: [
      ["(♥ω♥*)", "eyes"],
      "(´∀｀)♡",
      ["(｡♥‿♥｡)", "eyes"],
      ["♡(｡ˇ﹃ˇ｡)", "drool"],
      ["(ﾉ´ з `)ノ", "kiss"],
      ["(灬ºωº灬)", "blush"],
      ["(♡μ_μ)", "shy"],
      "♡＾▽＾♡",
      ["(´ε｀ )♡", "kiss"],
      "(｡•́‿•̀｡)♡",
      "ヽ(♡‿♡)ノ",
      ["(´,,•ω•,,)♡", "shy"],
      "(∗ ˃ᴗ˂)ꕤ*.゚",
      ["( ˘ ³˘)♥", "kiss"],
      ["(✿ ♥‿♥)", "flower eyes"],
      ["(っ˘з(˘⌣˘ ) ♡", "kiss couple"],
      "♡( ◡‿◡ )",
      ["(*˘︶˘*).｡*♡", "dreamy"],
      ["σ(≧ε≦σ) ♡", "kiss"],
      ["(◍•ᴗ•◍)❤", "cute"],
    ],
  },
  {
    name: "Hugs",
    keywords: "hug hugs cuddle embrace comfort squeeze",
    items: [
      "(っ´▽`)っ",
      ["(つ≧▽≦)つ", "excited"],
      "⊂(・▽・⊂)",
      ["(づ｡◕‿‿◕｡)づ", "cute"],
      ["(っ◔◡◔)っ ♥", "love"],
      ["⊂(´• ω •`⊂)", "soft"],
      ["(づ ￣ ³￣)づ", "kiss"],
      ["(⊃｡•́‿•̀｡)⊃", "offer"],
      ["(つ✧ω✧)つ", "sparkle"],
      ["♡(っ˘ω˘)っ", "love"],
      ["ʕっ•ᴥ•ʔっ", "bear"],
      ["(っಠ‿ಠ)っ", "creepy"],
      ["(o・_・)ノ”(ᴗ_ ᴗ。)", "headpat pat comfort"],
    ],
  },
  {
    name: "Sad",
    keywords: "sad cry crying tears upset sob unhappy depressed heartbroken broken",
    items: [
      "(｡•́︿•̀｡)",
      ["(ಥ_ಥ)", "tears"],
      ["。゜(´Ｔ▽Ｔ｀)゜。", "wail"],
      ["(╥﹏╥)", "tears"],
      ["(っ˘̩╭╮˘̩)っ", "comfort hug"],
      ["(´；ω；`)", "tears"],
      "(TヘT)",
      "(个_个)",
      "ㅠ_ㅠ",
      ["(ノ_<。)", "wipe tears"],
      "(͒˃̩̩⌂˂̩̩ )",
      ["(´-ω-`)", "sigh"],
      ["(ಥ﹏ಥ)", "sob"],
      ["(；へ：)", "pout"],
      ["(╯︵╰,)", "tear"],
      ["(ノ﹏ヽ)", "hide face"],
      ["(ㄒoㄒ)", "wail"],
      ["(｡ŏ﹏ŏ)", "worried"],
      ["( ; ω ; )", "tears"],
      ["o(TヘTo)", "tears"],
    ],
  },
  {
    name: "Angry",
    keywords: "angry mad rage furious annoyed grumpy",
    items: [
      "(╬ಠ益ಠ)",
      "٩(ఠ益ఠ)۶",
      ["щ(ﾟДﾟщ)", "why"],
      ["(`皿´)", "teeth"],
      ["ヽ(`Д´)ﾉ", "shout"],
      "(ﾒ` ﾛ ´)",
      "٩(๑`^´๑)۶",
      ["(#`Д´)", "shout"],
      ["ಠ_ಠ", "disapproval stare look"],
      ["(ノ｀Д´)ノ", "shout"],
      "(╬ Ò﹏Ó)",
      ["(｀皿´＃)", "teeth"],
      "ヽ(｀⌒´メ)ノ",
      ["凸(｀△´＃)", "middle finger"],
      ["(・`ω´・)", "pout"],
      ["( ｰ̀εｰ́ )", "pout sulk"],
      ["(¬_¬)", "side eye annoyed"],
      ["ಠ益ಠ", "rage"],
    ],
  },
  {
    name: "Unimpressed",
    keywords: "unimpressed facepalm deadpan bruh disgust disgusted ew gross cringe unamused eyeroll blank stare",
    items: [
      ["(－‸ლ)", "facepalm"],
      ["(ლ‸－)", "facepalm"],
      ["(／。＼)", "facepalm cringe"],
      ["(￣ヘ￣)", "pout"],
      ["(￢_￢)", "side eye"],
      ["(⇀_⇀)", "side eye"],
      ["(ㆆ _ ㆆ)", "stare"],
      ["(눈_눈)", "suspicious stare"],
      ["(￣_￣)", "deadpan"],
      ["( ・_・)", "deadpan"],
      ["(゜-゜)", "blank"],
      ["(；￣Д￣)", "ew gross"],
      ["(´-﹏-`；)", "cringe"],
      ["(~_~;)", "ugh"],
      ["(￣ω￣;)", "awkward"],
    ],
  },
  {
    name: "Nervous",
    keywords: "nervous scared fear afraid panic anxious awkward sweat worried",
    items: [
      ["(((;ꏿ_ꏿ;)))", "shaking"],
      ["ヽ(ﾟДﾟ)ﾉ", "panic"],
      ["(ﾉﾟ0ﾟ)ﾉ~", "run"],
      "(;;;*_*)",
      ["(ﾟДﾟ;)", "shock"],
      ["Σ(°△°|||)︴", "shock"],
      ["(・_・;)", "sweat"],
      ["(^_^;)", "laugh sweat"],
      ["(￣▽￣;)", "sweat"],
      "(⊙﹏⊙)",
      ["(゜ロ゜;)", "shock"],
      ["(>_<)", "wince"],
      ["〣( ºΔº )〣", "panic"],
      ["(°ー°〃)", "sweat"],
    ],
  },
  {
    name: "Sick & Dizzy",
    keywords: "sick ill unwell dizzy dead ko faint queasy nauseous hurt",
    items: [
      "(＠_＠)",
      "(@_@)",
      ["(◎_◎;)", "spinning"],
      ["(×_×)", "dead ko"],
      ["(x_x)", "dead ko"],
      ["(✖╭╮✖)", "dead"],
      ["(+_+)", "ko"],
      ["(´×ω×`)", "faint"],
      ["_(ˇωˇ」∠)_", "dead lying flop"],
      ["(☉_☉)", "stunned"],
      ["(-﹏-。)", "unwell"],
      ["(*´﹏`*)", "unwell"],
      ["(´～`;)", "queasy"],
      ["(ꏿ﹏ꏿ;)", "sick"],
    ],
  },
  {
    name: "Surprised",
    keywords: "surprised shock shocked wow gasp omg amazed",
    items: [
      "(⊙_⊙)",
      "Σ(ﾟДﾟ)",
      "(ﾟoﾟ)",
      "(°o°)",
      "(⊙ω⊙)",
      "ヽ(ﾟ〇ﾟ)ﾉ",
      "(๑•̀ㅁ•́๑)",
      "Σ(ಠ_ಠ)",
      "(ﾉ゜ロ゜)ノ",
      "(ノ°ο°)ノ",
      "w(°ｏ°)w",
      "(〇o〇；)",
      ["⊙▃⊙", "stare"],
    ],
  },
  {
    name: "Confused",
    keywords: "confused huh what question puzzled hmm thinking",
    items: [
      "(・_・ヾ",
      "( ◎o◎)",
      "(⊙_☉)",
      "(￢_￢;)",
      "(・・;)",
      "（＾ω＾;）",
      "(¿ °-°)¿",
      "(´･_･`)",
      "(・・ )?",
      "(¯ . ¯٥)",
      "(⊙_⊙)？",
      ["(｡･ω･｡)?", "cute"],
      ["(￣～￣;)", "think"],
      ["(・へ・)", "skeptical"],
      ["( ˘･_･˘)", "think"],
    ],
  },
  {
    name: "Shrug",
    keywords: "shrug whatever idk dunno meh",
    items: [
      "¯\\_(ツ)_/¯",
      "┐(￣ヘ￣)┌",
      "╮(￣ω￣)╭",
      "┐('～`;)┌",
      "＼(￣∇￣)/",
      "ヽ(ー_ー )ノ",
      "┐(￣～￣)┌",
      "╮(╯∀╰)╭",
      ["¯\\(°_o)/¯", "confused"],
      "ㄟ( ▔, ▔ )ㄏ",
      "┐(￣ー￣)┌",
      ["¯\\_(ಠ_ಠ)_/¯", "unimpressed"],
    ],
  },
  {
    name: "Table Flip",
    keywords: "table flip tableflip rage throw",
    items: [
      "(╯°□°）╯︵ ┻━┻",
      "(ノಠ益ಠ)ノ彡┻━┻",
      ["┻━┻ ︵ ¯\\(ツ)/¯ ︵ ┻━┻", "double"],
      ["(╯°Д°)╯︵/(.□ . \\)", "person throw"],
      "(ノ# ﾟДﾟ)ノ┻━┻・. ・",
      ["┬─┬ノ( º _ ºノ)", "unflip put back calm"],
      ["(-.-)凸", "middle finger"],
      ["┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻", "double"],
      "(ノ ゜Д゜)ノ ︵ ┻━┻",
      ["(ヘ･_･)ヘ┳━┳", "unflip put back"],
      "(╯ರ ~ ರ)╯︵ ┻━┻",
    ],
  },
  {
    name: "Blush",
    keywords: "blush shy embarrassed flustered bashful",
    items: [
      ["(*/ω＼*)", "hide"],
      "(〃ω〃)",
      "(ﾉ▽〃)",
      ["(*ﾉωﾉ)", "hide"],
      "(´⌣`ʃƪ)",
      "(๑>؂•̀๑)",
      ["(*/∇＼*)", "hide"],
      "(⁄ ⁄•⁄ω⁄•⁄ ⁄)",
      "(〃▽〃)",
      "(//ω//)",
      "(⁄ ⁄>⁄ ▽ ⁄<⁄ ⁄)",
      "(„ಡωಡ„)",
      "(*^.^*)",
    ],
  },
  {
    name: "Peeking",
    keywords: "peek peeking hide hiding lurk lurking wall sneak spy watching",
    items: [
      "|ω･)",
      "|･ω･)",
      ["|ω･)ﾉ", "wave hi"],
      ["|д･)", "stare"],
      "|_・)",
      ["|•ᴗ•)", "cute"],
      ["|▽//)", "shy"],
      ["ヾ|￣ー￣)", "smug"],
      ["|ʘ‿ʘ)╯", "creepy wave"],
      ["┬┴┬┴┤(･_├┬┴┬┴", "wall"],
      ["┬┴┬┴┤ω･`)", "wall"],
      ["┬┴┬┴┤･ω･)ﾉ", "wall wave"],
      ["(/▽＼)", "hide face"],
      ["(/ω＼)", "hide face"],
    ],
  },
  {
    name: "Mischief",
    keywords: "mischief evil smirk sneaky smug devious villain",
    items: [
      "(≖ᴗ≖✿)",
      "( ✧≖ ‿ ≖)",
      "(｀ε´)",
      "(¬‿¬)",
      ["( ͡° ͜ʖ ͡°)", "lenny"],
      "(≖͈̀ᴗ≖͈́)",
      ["( ͡~ ͜ʖ ͡°)", "lenny wink"],
      ["( ͡ʘ ͜ʖ ͡ʘ)", "lenny stare"],
      ["(ʘ‿ʘ)", "creepy stare"],
      "(￢‿￢ )",
      "(≖ ︿ ≖ ✿)",
      ["ψ(｀∇´)ψ", "devil"],
      "(≖ᴗ≖๑)",
    ],
  },
  {
    name: "Cool",
    keywords: "cool sunglasses shades deal with it chill swag",
    items: [
      "(⌐■_■)",
      ["( •_•)>⌐■-■", "put on"],
      ["(•_•) ( •_•)>⌐■-■ (⌐■_■)", "deal with it put on"],
      "(▀̿Ĺ̯▀̿ ̿)",
      ["(⌐■_■)ノ", "wave"],
      ["(⌐■_■)☞", "finger gun"],
      ["(っ▀¯▀)つ", "hug"],
      ["ᕕ(⌐■_■)ᕗ ♪♬", "strut walk"],
      ["(⌐□_□)", "glasses nerd"],
      ["(▰˘◡˘▰)", "relaxed"],
    ],
  },
  {
    name: "Cute",
    keywords: "cute soft sweet kawaii adorable uwu",
    items: [
      "(◕‿◕)",
      "(｡◕‿◕｡)",
      "(´• ω •`)",
      "(≧ω≦)",
      "(◍•ᴗ•◍)",
      "(￣ω￣)",
      "(๑•᎑•๑)",
      ["(っ´ω`c)", "cozy"],
      "(｡•ᴗ•｡)",
      ["(ᵕ—ᴗ—)", "content"],
      "(˶ᵔ ᵕ ᵔ˶)",
      "(◠‿◠)",
      ["(,,>﹏<,,)", "shy"],
      "( ˶ˆᗜˆ˵ )",
      "(๑ᵔ⤙ᵔ๑)",
      ["( ˘ω˘ )", "content"],
    ],
  },
  {
    name: "Animals",
    keywords: "animal animals pet",
    items: [
      ["(=^･ω･^=)", "cat kitty neko"],
      ["(=^-ω-^=)", "cat kitty sleepy"],
      ["^• ω •^", "cat kitty"],
      ["(=｀ω´=)", "cat kitty angry"],
      ["ฅ^•ﻌ•^ฅ", "cat kitty paws"],
      ["/ᐠ｡ꞈ｡ᐟ\\", "cat kitty"],
      ["(=ↀωↀ=)", "cat kitty"],
      ["ᓚᘏᗢ", "cat kitty"],
      ["=^..^=", "cat kitty"],
      ["ଲ(ⓛ ω ⓛ)ଲ", "cat kitty paws"],
      ["ʕ•ᴥ•ʔ", "bear"],
      ["ʕ ᵔᴥᵔ ʔ", "bear happy"],
      ["ʕ•̀ω•́ʔ✧", "bear determined"],
      ["(ᵔᴥᵔ)", "bear dog"],
      ["(￣(ｴ)￣)", "bear"],
      ["•ᴥ•", "bear dog"],
      ["U・ᴥ・U", "dog puppy"],
      ["∪･ω･∪", "dog puppy"],
      ["▼・ᴥ・▼", "dog puppy"],
      ["Ｕ^皿^Ｕ", "dog angry"],
      ["૮ ˶ᵔ ᵕ ᵔ˶ ა", "bunny puppy"],
      ["૮₍ ˃ ⤙ ˂ ₎ა", "bunny puppy"],
      ["／(≧ x ≦)＼", "bunny rabbit"],
      ["(・θ・)", "bird chick"],
      ["(•ө•)♡", "bird chick love"],
      ["<゜)))彡", "fish"],
      ["><((((º>", "fish"],
      ["( ´(00)ˋ )", "pig"],
      ["くコ:彡", "squid octopus"],
      ["~>゜)～～～", "snake"],
      ["(:3 っ)っ", "seal lying"],
      ["Ƹ̵̡Ӝ̵̨̄Ʒ", "butterfly"],
    ],
  },
  {
    name: "Sparkle",
    keywords: "sparkle sparkles sparkly magic wizard celebrate party star shine wand",
    items: [
      "☆*:.｡.o(≧▽≦)o.｡.:*☆",
      "(*＾▽＾)/",
      "✧*｡٩(ˊᗜˋ*)و✧*｡",
      "ପ(๑•ᴗ•๑)ଓ ♡",
      "*:.｡.☆",
      "(⁎˃ᴗ˂⁎)",
      ["(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧", "excited"],
      ["(つ˵•́ω•̀˵)つ━☆ﾟ.*･｡ﾟ", "spell"],
      ["(∩ᄑ_ᄑ)⊃━☆ﾟ*･｡*･:≡( ε:)", "spell zap"],
      ["╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ", "lenny spell"],
      "✧･ﾟ: *✧･ﾟ:*",
      ["☆彡", "shooting"],
      ["(ノ^_^)ノ☆", "throw"],
    ],
  },
  {
    name: "Dance & Music",
    keywords: "dance dancing music sing song party groove",
    items: [
      "┏(＾0＾)┛┗(＾0＾)┓",
      ["ヾ(⌐■_■)ノ♪", "cool"],
      "♪┏(・o･)┛♪",
      ["(~˘▾˘)~", "sway"],
      ["~(˘▾˘~)", "sway"],
      "(〜￣▽￣)〜",
      "〜(￣▽￣〜)",
      ["ᕕ( ᐛ )ᕗ", "happy walk skip"],
      ["♪～(´ε｀ )", "whistle"],
      "(￣▽￣)/♫•*¨*•.¸¸♪",
      "♪♪\\(^ω^\\ )( /^ω^)/♪♪",
      "ヽ(o´∀`)ﾉ♪♬",
      "(✧∀✧)/♪",
      "♬♩♪♩( ◜◒◝ )♩♪♩♬",
    ],
  },
  {
    name: "Food",
    keywords: "food eat eating drink drinks hungry yum tasty delicious snack coffee tea cheers",
    items: [
      "(っ˘ڡ˘ς)",
      ["( ˘▽˘)っ♨", "hot"],
      ["(￣～￣)", "chew"],
      "(*´ڡ`●)",
      "(○´ڡ`○)",
      ["( ﾟДﾟ)ｳﾏｰ", "umai"],
      ["( ˘⌣˘)旦", "tea cup"],
      ["( ´ ▽ ` )ﾉ旦", "tea cup offer"],
      ["( -_・)旦", "tea cup sip"],
      ["(*´▽`)っ旦~", "tea cup offer"],
      ["(*￣▽￣)旦 且_(・_・ )", "tea cup share"],
      ["( ´Ｏ｀)~旦", "tea cup relax"],
      ["( o˘◡˘o) ┌iii┐", "cake birthday"],
      ["(´～`ヾ)", "chew"],
      ["(○￣ω￣)=3", "full stuffed"],
      ["(〃´ڡ`)", "yummy"],
    ],
  },
  {
    name: "Cheers",
    keywords: "cheers toast kanpai drink drinks beer wine party celebrate bar",
    items: [
      "( ^_^)o自自o(^_^ )",
      "(＾▽＾)o自自o(＾▽＾)",
      "( ￣▽￣)[] [](≧▽≦ )",
      ["(^ω^)ノ凵", "cup"],
      ["(っ＾▽＾)っ凵", "cup offer"],
      ["(ﾉ´∀｀*)ﾉ凵", "cup"],
      ["ヽ(＾Д＾)ﾉ", "party"],
      ["(ﾉ´ヮ`)ﾉ*: ･ﾟ", "party"],
    ],
  },
  {
    name: "Fighting",
    keywords: "fight fighting punch battle strong flex muscle determined attack weapon weapons",
    items: [
      ["(ง'̀-'́)ง", "fists ready"],
      ["(ง •̀_•́)ง", "fists"],
      ["ლ(｀ー´ლ)", "fists"],
      ["(ﾒ` ﾛ ´)︻デ═一", "gun shoot"],
      ["(╯°□°)--︻╦╤─ - - -", "gun shoot"],
      ["( ・∀・)・・・--------☆", "throw"],
      ["(ᕗ ͠° ਊ ͠° )ᕗ", "rage"],
      "ᕦ(ò_óˇ)ᕤ",
      "ᕙ(⇀‸↼‶)ᕗ",
      "o(｀ω´ )o",
      ["(•̀ᴗ•́)و ̑̑", "go"],
      ["O=('-'Q)", "punch"],
      ["ʕง•ᴥ•ʔง", "bear"],
      ["(ﾒ▼ ▼)┏", "tough"],
      ["(　-_･) ︻デ═一 ▸", "gun sniper aim shoot"],
      ["(ﾒ￣▽￣)︻┳═一", "gun shoot"],
      ["▬▬ι═══════ﺤ", "sword"],
      ["-═══════ι▬▬", "sword"],
      ["(ﾉ･ｪ･)ﾉ ⌒●~*", "bomb throw"],
      ["―(T_T)→", "arrow hit ouch archer"],
    ],
  },
  {
    name: "Thumbs Up",
    keywords: "thumbs up ok okay good approve yes nice point pointing peace",
    items: [
      "(b ᵔ▽ᵔ)b",
      ["(๑•̀ㅂ•́)و✧", "determined"],
      "d(￣▽￣)b",
      "ｂ(￣▽￣)ｄ",
      "( •̀ᴗ•́ )و",
      "(￣ー￣)ｂ",
      "( ´ ▽ ` )b",
      ["(>ᴗ•)ｂ", "wink"],
      ["(ゝω・)v", "wink victory"],
      ["( ･ω･)☞", "finger"],
      ["(☞ﾟヮﾟ)☞", "finger guns"],
      ["☜(ﾟヮﾟ☜)", "finger guns"],
      "(o^▽^)o",
    ],
  },
  {
    name: "Sorry",
    keywords: "sorry apologize apology bow please thanks thank beg",
    items: [
      "m(_ _)m",
      "(シ_ _)シ",
      "<(_ _)>",
      "m(._.)m",
      ["(￣▽￣*)ゞ", "salute sheepish"],
      "(ᴗ_ ᴗ。)",
      ["(>人<;)", "pray"],
      ["(人´∀｀)", "pray"],
      ["(人 •͈ᴗ•͈)", "pray"],
      ["orz", "despair kneel"],
      ["OTL", "despair kneel"],
      ["m(_ _;)m", "sweat"],
      ["(〃￣ω￣〃)ゞ", "sheepish"],
      ["(ㅅ´ ˘ `)", "pray thanks grateful"],
      ["(´▽`ʃ♡ƪ)", "thanks grateful"],
    ],
  },
  {
    name: "Running",
    keywords: "run running hurry fast dash escape go chase",
    items: [
      "ε=ε=┌( >_<)┘",
      "ε=ε=ε=┌(;￣▽￣)┘",
      "C= C= C= C= C=┌(;・ω・)┘",
      ["─=≡Σ((( つ•̀ω•́)つ", "charge"],
      ["ε=┌( ≧▽≦)┘", "happy"],
      ["ε=ε=(ノ≧∇≦)ノ", "excited"],
      ["(っ・ω・）っ≡≡≡≡≡≡☆", "throw"],
      ["┌(ㆆ㉨ㆆ)ʃ", "walk"],
      "ε=ε=┏( >_<)┛",
      ["ε=ε=ε=(~￣▽￣)~", "happy"],
      ["三三ᕕ( ᐛ )ᕗ", "happy"],
      ["ε===(っ≧ω≦)っ", "excited"],
    ],
  },
  {
    name: "Busy",
    keywords: "busy work working write writing study studying note notes homework typing focus",
    items: [
      "φ(．．)",
      ["φ(゜▽゜*)♪", "happy"],
      "_φ(･_･",
      ["φ(^∇^ )", "happy"],
      ["_〆(。。)", "note"],
      ["〆(・∀・＠)", "note"],
      ["( •_•)⌨", "typing keyboard computer"],
      ["(｀・ω・´)ゞ", "salute on it"],
      ["(￣^￣)ゞ", "salute yes sir"],
      ["(＠_＠;)", "overwhelmed"],
      ["(´-ι_-｀)", "thinking tired"],
    ],
  },
  {
    name: "Money",
    keywords: "money cash rich dollar dollars pay paid bill bills broke poor greedy",
    items: [
      ["($ᴗ$)", "rich"],
      ["$_$", "greedy eyes"],
      ["(＄▽＄)", "greedy"],
      ["( ◕ᴗ◕)っ$", "give pay"],
      ["(╯°□°)╯$$$", "throw make it rain"],
      ["[̲̅$̲̅(̲̅5̲̅)̲̅$̲̅]", "bill five"],
      ["[̲̅$̲̅(̲̅ιοο̲̅)̲̅$̲̅]", "bill hundred"],
      ["[̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]", "bill lenny"],
      ["(｡•́︿•̀｡) $0", "broke poor"],
    ],
  },
  {
    name: "Sleepy",
    keywords: "sleepy sleep tired night bed nap zzz bored yawn",
    items: [
      "(-_-) zzZ",
      "(∪｡∪)｡｡｡zzz",
      "( ˘ω˘ )ｽﾔｧ",
      "(-.-)Zzz...",
      "(ᴗ_ᴗ)",
      "(＿ ＿*) Ｚｚｚ",
      "(っ˘ω˘)ﾉ",
      ["_(:3 」∠)_", "lazy lying flop"],
      "(－ω－) zzZ",
      "(´〜｀*) zzz",
      ["(=_=)", "bored"],
      "(ᴗ˳ᴗ)",
      ["(～﹃～)~zZ", "drool"],
      "(´-﹃-`)",
      "(_ _)。゜zｚＺ",
      ["(￣o￣) zzZZzzZZ", "snore"],
      ["(¦3[▓▓]", "blanket"],
    ],
  },
  {
    name: "Greetings",
    keywords: "hi hello hey bye goodbye wave greetings",
    items: [
      "(o･ω･o)ﾉ",
      "( ﾟ▽ﾟ)/",
      "(=ﾟωﾟ)ﾉ",
      "ヾ(＾-＾)ノ",
      "(￣▽￣)ノ",
      ["またね (^_^)/~~", "see you later"],
      "( ﾉ･ω･)ﾉ",
      "(・ω・)ﾉ",
      "( ´ ▽ ` )ﾉ",
      "(^-^*)/",
      "(*・ω・)ﾉ",
      "ヾ(・ω・*)",
      "ヾ(￣▽￣) Bye~Bye~",
      "(｡･∀･)ﾉﾞ",
      "(〃＾▽＾〃)ノ",
      "(⌒o⌒)ノ",
    ],
  },
];
